from __future__ import annotations

import ast
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS_FILE = ROOT / "requirements.txt"
AUDIT_DOC = ROOT / "docs" / "requirements_coverage_audit.md"

PRODUCTION_FILE_PATTERNS = [
    "main.py",
    "vision_config.py",
    "src/**/*.py",
]

IGNORE_TOP_LEVEL_MODULES = {"src", "vision_config", "main"}
REQUIREMENT_TO_IMPORT_MAPPING = {
    "google-genai": "google",
    "edge-tts": "edge_tts",
    "websocket-client": "websocket",
}


def _normalize_requirement_name(raw_name: str) -> str:
    return raw_name.strip().lower().replace("_", "-")


def _parse_requirements(path: Path) -> list[str]:
    declared: set[str] = set()
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        for marker in ("==", ">=", "<=", "~=", "!=", ">", "<"):
            if marker in line:
                line = line.split(marker, 1)[0].strip()
                break
        if line:
            declared.add(_normalize_requirement_name(line))
    return sorted(declared)


def _candidate_production_files() -> list[Path]:
    files: set[Path] = set()
    for pattern in PRODUCTION_FILE_PATTERNS:
        files.update(ROOT.glob(pattern))

    filtered = [
        p for p in files if p.is_file() and not any(part in {"tests", "__pycache__", ".venv", "venv"} for part in p.parts)
    ]
    return sorted(filtered)


def _discover_top_level_imports(files: list[Path]) -> tuple[set[str], list[str]]:
    imports: set[str] = set()
    skipped_files: list[str] = []
    for file_path in files:
        try:
            tree = ast.parse(file_path.read_text(encoding="utf-8"), filename=str(file_path))
        except (SyntaxError, UnicodeDecodeError):
            skipped_files.append(str(file_path.relative_to(ROOT)))
            continue

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.add(alias.name.split(".", 1)[0])
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.add(node.module.split(".", 1)[0])
    return imports, sorted(skipped_files)


def _build_requirement_import_names(requirements: list[str]) -> set[str]:
    expected: set[str] = set()
    for requirement in requirements:
        expected.add(requirement.replace("-", "_"))
    for requirement, import_name in REQUIREMENT_TO_IMPORT_MAPPING.items():
        if requirement in requirements:
            expected.add(import_name)
    return expected


def _render_markdown(
    requirements: list[str],
    discovered_third_party: list[str],
    likely_missing: list[str],
    ignored_imports: list[str],
    scanned_files: list[str],
    skipped_files: list[str],
) -> str:
    lines = [
        "# Requirements Coverage Audit",
        "",
        "This file is auto-generated by `tests/test_requirements_coverage_audit.py`.",
        "",
        "## Exact command used",
        "",
        "- `pytest -q tests/test_requirements_coverage_audit.py`",
        "",
        "## Scanned production files",
        "",
    ]
    lines.extend(f"- `{path}`" for path in scanned_files)

    lines.extend([
        "",
        "## Skipped files (parse errors)",
        "",
    ])
    lines.extend(f"- `{path}`" for path in skipped_files)

    lines.extend([
        "",
        "## Declared dependencies (requirements.txt)",
        "",
    ])
    lines.extend(f"- `{item}`" for item in requirements)

    lines.extend([
        "",
        "## Discovered third-party imports",
        "",
    ])
    lines.extend(f"- `{item}`" for item in discovered_third_party)

    lines.extend([
        "",
        "## Likely missing declarations",
        "",
    ])
    lines.extend(f"- `{item}`" for item in likely_missing)

    lines.extend([
        "",
        "## Ignored stdlib/local imports",
        "",
    ])
    lines.extend(f"- `{item}`" for item in ignored_imports)
    lines.append("")

    return "\n".join(lines)


def test_requirements_coverage_audit_document_is_updated() -> None:
    requirements = _parse_requirements(REQUIREMENTS_FILE)
    production_files = _candidate_production_files()
    discovered_imports, skipped_files = _discover_top_level_imports(production_files)

    stdlib_modules = set(sys.stdlib_module_names)
    ignored_imports = sorted(name for name in discovered_imports if name in stdlib_modules or name in IGNORE_TOP_LEVEL_MODULES)

    discovered_third_party = sorted(
        name
        for name in discovered_imports
        if name not in stdlib_modules and name not in IGNORE_TOP_LEVEL_MODULES
    )

    declared_import_names = _build_requirement_import_names(requirements)
    likely_missing = sorted(name for name in discovered_third_party if name not in declared_import_names)

    document = _render_markdown(
        requirements=requirements,
        discovered_third_party=discovered_third_party,
        likely_missing=likely_missing,
        ignored_imports=ignored_imports,
        scanned_files=[str(path.relative_to(ROOT)) for path in production_files],
        skipped_files=skipped_files,
    )

    AUDIT_DOC.write_text(document, encoding="utf-8")
